AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  PgpKeyLocation:
    Type: String
    Description: "S3 bucket where the PGP private key is located"
  PgpKeyName:
    Type: String
    Description: "Name of the PGP private key"
  DecryptedTargetBucket:
    Type: String
    Description: "S3 Bucket where files will land lambda decryption"
  EncryptedSourceBucket:
    Type: String
    Description: "S3 Bucket that triggers lambda to decrypt files. Needed for permissions"
Resources:
  PgpLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: pgplambda.lambda_handler
      CodeUri: src
      Layers:
        - !Ref GpgDependencies
      Runtime: python3.9
      Timeout: 300
      MemorySize: 128
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "s3:ListBucket"
              Resource:
                - !Sub "arn:aws:s3:::${DecryptedTargetBucket}"
                - !Sub "arn:aws:s3:::${EncryptedSourceBucket}"
                - !Sub "arn:aws:s3:::${PgpKeyLocation}"
            - Effect: "Allow"
              Action:
                - "s3:PutObject"
                - "s3:GetObject"
                - "s3:DeleteObject"
              Resource:
                - !Sub "arn:aws:s3:::${DecryptedTargetBucket}/*"
                - !Sub "arn:aws:s3:::${EncryptedSourceBucket}/*"
                - !Sub "arn:aws:s3:::${PgpKeyLocation}/*"
      Environment:
        Variables:
          PGP_KEY_LOCATION:
            Ref: PgpKeyLocation
          PGP_KEY_NAME:
            Ref: PgpKeyName
          DECRYPTED_DONE_BUCKET:
            Ref: DecryptedTargetBucket
  GpgDependencies:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: gnupg-layer
      Description: Dependencies for GPG decription
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.9

